import type {
  TwColorSemantic,
  TwScreenStyle,
  TwTextAlign,
  TwTextClampAmount,
  TwTextDecoration,
  TwTextSize,
  TwTextTransform,
  TwTextWeight,
} from '../types'

export const TW_CLS_TEXT_SIZE_SCREEN: TwScreenStyle<TwTextSize> = {
  default: {
    '2xs': 'text-2xs',
    xs: 'text-xs',
    sm: 'text-sm',
    base: 'text-base',
    lg: 'text-lg',
    xl: 'text-xl',
    '2xl': 'text-2xl',
    '3xl': 'text-3xl',
    '4xl': 'text-4xl',
    '5xl': 'text-5xl',
    '6xl': 'text-6xl',
    '7xl': 'text-7xl',
    '8xl': 'text-8xl',
    '9xl': 'text-9xl',
  },
  xs: {
    '2xs': 'xs:text-2xs',
    xs: 'xs:text-xs',
    sm: 'xs:text-sm',
    base: 'xs:text-base',
    lg: 'xs:text-lg',
    xl: 'xs:text-xl',
    '2xl': 'xs:text-2xl',
    '3xl': 'xs:text-3xl',
    '4xl': 'xs:text-4xl',
    '5xl': 'xs:text-5xl',
    '6xl': 'xs:text-6xl',
    '7xl': 'xs:text-7xl',
    '8xl': 'xs:text-8xl',
    '9xl': 'xs:text-9xl',
  },
  sm: {
    '2xs': 'sm:text-2xs',
    xs: 'sm:text-xs',
    sm: 'sm:text-sm',
    base: 'sm:text-base',
    lg: 'sm:text-lg',
    xl: 'sm:text-xl',
    '2xl': 'sm:text-2xl',
    '3xl': 'sm:text-3xl',
    '4xl': 'sm:text-4xl',
    '5xl': 'sm:text-5xl',
    '6xl': 'sm:text-6xl',
    '7xl': 'sm:text-7xl',
    '8xl': 'sm:text-8xl',
    '9xl': 'sm:text-9xl',
  },
  md: {
    '2xs': 'md:text-2xs',
    xs: 'md:text-xs',
    sm: 'md:text-sm',
    base: 'md:text-base',
    lg: 'md:text-lg',
    xl: 'md:text-xl',
    '2xl': 'md:text-2xl',
    '3xl': 'md:text-3xl',
    '4xl': 'md:text-4xl',
    '5xl': 'md:text-5xl',
    '6xl': 'md:text-6xl',
    '7xl': 'md:text-7xl',
    '8xl': 'md:text-8xl',
    '9xl': 'md:text-9xl',
  },
  lg: {
    '2xs': 'lg:text-2xs',
    xs: 'lg:text-xs',
    sm: 'lg:text-sm',
    base: 'lg:text-base',
    lg: 'lg:text-lg',
    xl: 'lg:text-xl',
    '2xl': 'lg:text-2xl',
    '3xl': 'lg:text-3xl',
    '4xl': 'lg:text-4xl',
    '5xl': 'lg:text-5xl',
    '6xl': 'lg:text-6xl',
    '7xl': 'lg:text-7xl',
    '8xl': 'lg:text-8xl',
    '9xl': 'lg:text-9xl',
  },
  xl: {
    '2xs': 'xl:text-2xs',
    xs: 'xl:text-xs',
    sm: 'xl:text-sm',
    base: 'xl:text-base',
    lg: 'xl:text-lg',
    xl: 'xl:text-xl',
    '2xl': 'xl:text-2xl',
    '3xl': 'xl:text-3xl',
    '4xl': 'xl:text-4xl',
    '5xl': 'xl:text-5xl',
    '6xl': 'xl:text-6xl',
    '7xl': 'xl:text-7xl',
    '8xl': 'xl:text-8xl',
    '9xl': 'xl:text-9xl',
  },
} as const

export const TW_CLS_TEXT_COLOR: { [key in TwColorSemantic]: string } = {
  default: 'text-default',
  primary: 'text-primary',
  secondary: 'text-secondary',
  tertiary: 'text-tertiary',
  accent: 'text-accent',
  success: 'text-success',
  danger: 'text-danger',
  warning: 'text-warning',
  info: 'text-info',
  content: 'text-content',
  black: 'text-black',
  white: 'text-white',
  zinc: 'text-zinc-500',
  neutral: 'text-neutral-300',
} as const

export const TW_CLS_TEXT_WEIGHT: { [key in TwTextWeight]: string } = {
  thin: 'font-thin',
  extralight: 'font-extralight',
  light: 'font-light',
  normal: 'font-normal',
  medium: 'font-medium',
  semibold: 'font-semibold',
  bold: 'font-bold',
  extrabold: 'font-extrabold',
  black: 'font-black',
} as const

export const TW_CLS_TEXT_DECORATION: { [key in TwTextDecoration]: string } = {
  underline: 'underline',
  'line-through': 'line-through',
  'no-underline': 'no-underline',
  overline: 'overline',
} as const

export const TW_CLS_TEXT_TRANSFORM: { [key in TwTextTransform]: string } = {
  lowercase: 'lowercase',
  uppercase: 'uppercase',
  capitalize: 'capitalize',
  'normal-case': 'normal-case',
} as const

export const TW_CLS_TEXT_ALIGN_SCREEN: TwScreenStyle<TwTextAlign> = {
  default: {
    left: 'text-left',
    center: 'text-center',
    right: 'text-right',
    justify: 'text-justify',
  },
  xs: {
    left: 'xs:text-left',
    center: 'xs:text-center',
    right: 'xs:text-right',
    justify: 'xs:text-justify',
  },
  sm: {
    left: 'sm:text-left',
    center: 'sm:text-center',
    right: 'sm:text-right',
    justify: 'sm:text-justify',
  },
  md: {
    left: 'md:text-left',
    center: 'md:text-center',
    right: 'md:text-right',
    justify: 'md:text-justify',
  },
  lg: {
    left: 'lg:text-left',
    center: 'lg:text-center',
    right: 'lg:text-right',
    justify: 'lg:text-justify',
  },
  xl: {
    left: 'xl:text-left',
    center: 'xl:text-center',
    right: 'xl:text-right',
    justify: 'xl:text-justify',
  },
} as const

export const TW_CLS_TEXT_CLAMP_SCREEN: TwScreenStyle<TwTextClampAmount> = {
  default: {
    1: 'line-clamp-1',
    2: 'line-clamp-2',
    3: 'line-clamp-3',
    4: 'line-clamp-4',
    5: 'line-clamp-5',
    6: 'line-clamp-6',
    none: 'line-clamp-none',
  },
  xs: {
    1: 'xs:line-clamp-1',
    2: 'xs:line-clamp-2',
    3: 'xs:line-clamp-3',
    4: 'xs:line-clamp-4',
    5: 'xs:line-clamp-5',
    6: 'xs:line-clamp-6',
    none: 'xs:line-clamp-none',
  },
  sm: {
    1: 'sm:line-clamp-1',
    2: 'sm:line-clamp-2',
    3: 'sm:line-clamp-3',
    4: 'sm:line-clamp-4',
    5: 'sm:line-clamp-5',
    6: 'sm:line-clamp-6',
    none: 'sm:line-clamp-none',
  },
  md: {
    1: 'md:line-clamp-1',
    2: 'md:line-clamp-2',
    3: 'md:line-clamp-3',
    4: 'md:line-clamp-4',
    5: 'md:line-clamp-5',
    6: 'md:line-clamp-6',
    none: 'md:line-clamp-none',
  },
  lg: {
    1: 'lg:line-clamp-1',
    2: 'lg:line-clamp-2',
    3: 'lg:line-clamp-3',
    4: 'lg:line-clamp-4',
    5: 'lg:line-clamp-5',
    6: 'lg:line-clamp-6',
    none: 'lg:line-clamp-none',
  },
  xl: {
    1: 'xl:line-clamp-1',
    2: 'xl:line-clamp-2',
    3: 'xl:line-clamp-3',
    4: 'xl:line-clamp-4',
    5: 'xl:line-clamp-5',
    6: 'xl:line-clamp-6',
    none: 'xl:line-clamp-none',
  },
} as const
