import {
  // AiOutlineAppstore,
  AiOutlineArrowLeft,
  // AiOutlineCalendar,
  AiOutlineCheck,
  AiOutlineClose,
  // AiOutlineComment,
  AiOutlineDelete,
  // AiOutlineDollar,
  AiOutlineDown,
  // AiOutlineDownload,
  // AiOutlineEdit,
  AiOutlineEye,
  AiOutlineFile,
  AiOutlineFileDone,
  // AiOutlineGift,
  // AiOutlineHome,
  // AiOutlineInbox,
  AiOutlineLeft,
  // AiOutlineLineChart,
  AiOutlineLogout,
  AiOutlineMail,
  // AiOutlineMenu,
  // AiOutlineMenuFold,
  // AiOutlineMenuUnfold,
  // AiOutlineMessage,
  // AiOutlineNotification,
  AiOutlinePhone,
  AiOutlinePlus,
  AiOutlineMinus,
  // AiOutlinePlusCircle,
  AiOutlineRight,
  AiOutlineSearch,
  AiOutlineSetting,
  AiOutlineUpload,
  AiOutlineUser,
  AiOutlineFileText,
  AiOutlineEnvironment,
  AiOutlineCloudUpload,
  AiOutlineReload,
  AiOutlineLoading,
  AiOutlineCheckCircle,
  AiOutlineCloseCircle,
  AiOutlineShopping,
  AiOutlinePrinter,
  AiOutlineClockCircle,
  AiOutlineExclamationCircle,
  AiOutlineInfoCircle,
  AiOutlineFileExclamation,
} from 'react-icons/ai'
import { FaFacebookF, FaInstagram, FaTwitter, FaYoutube } from 'react-icons/fa'

export const ReactIcon = {
  // Ant Design Icons
  AiOutlineSearch,
  AiOutlinePlus,
  AiOutlineMinus,
  AiOutlineCheck,
  AiOutlineClose,
  AiOutlineArrowLeft,
  AiOutlineLeft,
  AiOutlineRight,
  AiOutlineDown,
  AiOutlineDelete,
  AiOutlineEye,
  AiOutlineFile,
  AiOutlineFileDone,
  AiOutlineFileText,
  AiOutlineUpload,
  AiOutlineCloudUpload,
  AiOutlineReload,
  AiOutlineLoading,
  AiOutlineCheckCircle,
  AiOutlineCloseCircle,
  AiOutlineShopping,
  AiOutlineUser,
  AiOutlineSetting,
  AiOutlineLogout,
  AiOutlineMail,
  AiOutlinePhone,
  AiOutlineEnvironment,
  AiOutlinePrinter,
  AiOutlineClockCircle,
  AiOutlineExclamationCircle,
  AiOutlineInfoCircle,
  AiOutlineFileExclamation,
  FaFacebookF,
  FaYoutube,
  FaInstagram,
  FaTwitter,
}
